import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Menu as MenuIcon,X,ShoppingBag,Heart,Star,ArrowRight,MapPin,Clock3,Phone,Mail,Instagram,Facebook,ChevronDown,Plus,Minus,Trash2,Check,ChefHat,CakeSlice,Croissant,Send} from 'lucide-react';
import './index.css';

const IMG={
 hero:'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=1400&q=88',
 croissant:'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=85',
 chocolate:'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=85',
 plum:'https://images.unsplash.com/photo-1576618148400-8f8f5e4b3a7a?auto=format&fit=crop&w=900&q=85',
 bread:'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=900&q=85',
 pistachio:'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?auto=format&fit=crop&w=900&q=85',
 coffee:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=85',
 baker:'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1200&q=85',
 interior:'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=1100&q=85',
 cake:'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1200&q=85',
 tart:'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=900&q=85',
 dessert:'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=900&q=85',
 coffee2:'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=900&q=85',
};
const products=[
{id:1,name:'Butter Croissant',price:120,cat:'Pastries',desc:'Flaky, buttery and freshly baked.',img:IMG.croissant},
{id:2,name:'Belgian Chocolate Cake',price:650,cat:'Cakes',desc:'Rich chocolate layers with silky ganache.',img:IMG.chocolate},
{id:3,name:'Classic Plum Cake',price:450,cat:'Cakes',desc:'A festive Indian bakery classic.',img:IMG.plum},
{id:4,name:'Masala Bun',price:80,cat:'Breads',desc:'Soft, savory and packed with Indian spices.',img:IMG.bread},
{id:5,name:'Rasmalai Tres Leches',price:750,cat:'Indian Fusion',desc:'A modern fusion of rasmalai and tres leches.',img:IMG.dessert},
{id:6,name:'Pistachio Rose Cake',price:700,cat:'Cakes',desc:'Delicate pistachio sponge with rose cream.',img:IMG.pistachio},
];
const categories=['All','Cakes','Pastries','Breads','Indian Fusion','Desserts','Beverages'];
function Button({children,secondary=false,onClick,className=''}){return <button onClick={onClick} className={`inline-flex items-center justify-center gap-2 rounded-full px-5 py-3 text-sm font-semibold transition-all duration-300 hover:-translate-y-0.5 ${secondary?'border border-rose/50 bg-white/50 text-chocolate hover:bg-white':'bg-chocolate text-ivory shadow-lg shadow-chocolate/10 hover:bg-mocha'} ${className}`}>{children}</button>}
function SectionTitle({eyebrow,title,children}){return <div className="mb-10 max-w-2xl"><p className="mb-2 text-xs font-bold uppercase tracking-[.22em] text-rose">{eyebrow}</p><h2 className="serif text-4xl font-semibold leading-tight text-chocolate md:text-5xl">{title}</h2>{children&&<p className="mt-4 leading-7 text-chocolate/65">{children}</p>}</div>}
function Navbar({cartCount,onCart}){const[open,setOpen]=useState(false);const links=[['Home','#home'],['Menu','#menu'],['Our Story','#story'],['Specialties','#specialties'],['Contact','#contact']];return <header className="fixed left-0 right-0 top-0 z-50 px-4 pt-4"><nav className="mx-auto flex max-w-7xl items-center justify-between rounded-[22px] border border-white/70 bg-ivory/75 px-4 py-3 shadow-lg shadow-chocolate/5 backdrop-blur-xl md:px-6"><a href="#home" className="flex items-center gap-3" onClick={()=>setOpen(false)}><span className="grid h-10 w-10 place-items-center rounded-2xl bg-chocolate text-ivory"><Croissant size={21}/></span><span className="serif text-xl font-semibold">Crème <span className="text-rose">&</span> Crust</span></a><div className="hidden items-center gap-7 md:flex">{links.map(([l,h])=><a key={l} href={h} className="text-sm font-medium text-chocolate/75 transition hover:text-chocolate">{l}</a>)}</div><div className="flex items-center gap-2"><button onClick={onCart} className="relative grid h-10 w-10 place-items-center rounded-full hover:bg-white/70"><ShoppingBag size={19}/>{cartCount>0&&<span className="absolute -right-0.5 -top-0.5 grid h-5 w-5 place-items-center rounded-full bg-rose text-[10px] font-bold text-white">{cartCount}</span>}</button><Button className="hidden sm:inline-flex">Order Now</Button><button className="grid h-10 w-10 place-items-center rounded-full md:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<MenuIcon/>}</button></div>{open&&<div className="absolute left-0 right-0 top-[74px] rounded-[22px] border border-white/70 bg-ivory/95 p-4 shadow-xl backdrop-blur-xl md:hidden">{links.map(([l,h])=><a onClick={()=>setOpen(false)} key={l} href={h} className="block rounded-xl px-4 py-3 font-medium hover:bg-white/70">{l}</a>)}<Button className="mt-2 w-full">Order Now</Button></div>}</nav></header>}
function Hero(){return <section id="home" className="grain relative overflow-hidden px-5 pb-20 pt-36 md:pb-28 md:pt-44"><div className="absolute -left-28 top-28 h-80 w-80 rounded-full bg-rose/15 blur-3xl"/><div className="absolute -right-20 top-10 h-96 w-96 rounded-full bg-mocha/10 blur-3xl"/><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.9fr_1.1fr]"><div className="relative z-10"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-rose/35 bg-white/55 px-4 py-2 text-xs font-semibold text-mocha backdrop-blur">✦ Freshly Baked <span className="text-rose">•</span> Every Morning</div><h1 className="serif max-w-xl text-5xl font-semibold leading-[1.03] tracking-tight text-chocolate sm:text-6xl lg:text-7xl">A Little Taste of <span className="text-mocha">Home,</span> Baked Fresh.</h1><p className="mt-6 max-w-lg text-base leading-7 text-chocolate/65">Handcrafted breads, delicate pastries, celebration cakes and Indian-inspired treats — baked in small batches with warmth and tradition.</p><div className="mt-8 flex flex-wrap gap-3"><Button onClick={()=>document.querySelector('#menu').scrollIntoView({behavior:'smooth'})}>Explore Our Menu <ArrowRight size={17}/></Button><Button secondary>Order a Celebration Cake</Button></div><div className="mt-9 flex items-center gap-4 text-sm text-chocolate/60"><div className="flex -space-x-2">{['photo-1494790108377-be9c29b29330','photo-1500648767791-00dcc994a43e','photo-1535713875002-d1d0cf377fde'].map(x=><img key={x} className="h-9 w-9 rounded-full border-2 border-ivory object-cover" src={`https://images.unsplash.com/${x}?auto=format&fit=crop&w=100&q=75`}/>)}</div><span><b className="text-chocolate">4.9/5</b> from 1,000+ happy customers</span></div></div><div className="relative mx-auto w-full max-w-2xl"><div className="hero-orb absolute -inset-5 rounded-[42px] bg-gradient-to-br from-rose/25 via-white/10 to-mocha/20"/><div className="glass img-zoom relative overflow-hidden rounded-[34px] p-3"><img src={IMG.hero} className="h-[440px] w-full rounded-[27px] object-cover md:h-[570px]"/><div className="absolute bottom-7 left-7 glass rounded-2xl px-4 py-3"><p className="text-xs font-semibold text-mocha">BAKED TODAY</p><p className="serif text-lg font-semibold">Warm from the oven</p></div></div><div className="glass absolute -left-4 top-10 rounded-2xl px-4 py-3 shadow-glass md:-left-8"><p className="text-sm font-semibold">♡ Made with Love</p></div><div className="glass absolute -right-3 bottom-28 rounded-2xl px-4 py-3 shadow-glass md:-right-8"><p className="text-sm font-semibold">✓ 100% Eggless Options</p></div></div></div></section>}
function ProductCard({p,onAdd,onFav,fav}){return <article className="glass lift overflow-hidden rounded-[25px]"><div className="img-zoom relative overflow-hidden"><img src={p.img} className="h-64 w-full object-cover"/><button onClick={()=>onFav(p.id)} className={`absolute right-4 top-4 grid h-10 w-10 place-items-center rounded-full border border-white/70 bg-ivory/80 backdrop-blur ${fav?'text-rose':'text-chocolate'}`}><Heart size={18} fill={fav?'currentColor':'none'}/></button><span className="absolute bottom-4 left-4 rounded-full bg-chocolate/90 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-ivory">{p.cat}</span></div><div className="p-5"><h3 className="serif text-xl font-semibold">{p.name}</h3><p className="mt-1 min-h-10 text-sm leading-5 text-chocolate/60">{p.desc}</p><div className="mt-5 flex items-center justify-between"><span className="text-lg font-bold text-mocha">₹{p.price}</span><button onClick={()=>onAdd(p)} className="inline-flex items-center gap-2 rounded-full bg-chocolate px-4 py-2.5 text-xs font-semibold text-ivory transition hover:bg-mocha"><Plus size={15}/> Add to Cart</button></div></div></article>}
function MenuSection({onAdd,favs,onFav}){const[cat,setCat]=useState('All');const shown=useMemo(()=>cat==='All'?products:products.filter(p=>p.cat===cat),[cat]);return <section id="menu" className="bg-white/40 px-5 py-24"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="Fresh from the oven" title="Bakes worth coming back for." children="From flaky morning favourites to indulgent celebration cakes, every bake is made fresh in small batches."/><div className="hide-scroll mb-8 flex gap-2 overflow-x-auto pb-2">{categories.map(c=><button key={c} onClick={()=>setCat(c)} className={`whitespace-nowrap rounded-full px-5 py-2.5 text-sm font-semibold transition ${cat===c?'bg-chocolate text-ivory':'border border-rose/30 bg-white/50 text-chocolate/70 hover:bg-white'}`}>{c}</button>)}</div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{shown.map(p=><ProductCard key={p.id} p={p} onAdd={onAdd} onFav={onFav} fav={favs.includes(p.id)}/>)}</div></div></section>}
function Specialties(){const items=['Rasmalai Cake','Gulab Jamun Cheesecake','Kesar Pista Cake','Elaichi Milk Cake','Rose Pistachio Tart','Filter Coffee Tiramisu'];return <section id="specialties" className="grain overflow-hidden px-5 py-24"><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1.15fr_.85fr]"><div className="grid grid-cols-2 gap-4"><div className="img-zoom row-span-2 overflow-hidden rounded-[28px]"><img src={IMG.dessert} className="h-full min-h-[530px] w-full object-cover"/></div><div className="img-zoom overflow-hidden rounded-[28px]"><img src={IMG.tart} className="h-64 w-full object-cover"/></div><div className="glass flex items-end rounded-[28px] p-6"><div><p className="text-xs font-bold uppercase tracking-widest text-rose">The C&C signature</p><p className="serif mt-2 text-2xl font-semibold">Desi soul. Modern craft.</p></div></div></div><div><SectionTitle eyebrow="Indian specialties" title="Desi Flavours, Modern Bakes.">We blend familiar Indian flavours with contemporary pastry techniques — keeping the soul of the original, while giving it a new expression.</SectionTitle><div className="grid gap-3 sm:grid-cols-2">{items.map((x,i)=><div key={x} className="glass lift rounded-2xl p-4"><div className="mb-3 grid h-9 w-9 place-items-center rounded-xl bg-rose/15 text-mocha">{i+1}</div><p className="font-semibold">{x}</p><p className="mt-1 text-xs text-chocolate/50">Handcrafted in small batches</p></div>)}</div></div></div></section>}
function Story(){return <section id="story" className="bg-chocolate px-5 py-24 text-ivory"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div className="img-zoom overflow-hidden rounded-[32px] border border-white/10"><img src={IMG.baker} className="h-[500px] w-full object-cover"/></div><div><p className="mb-2 text-xs font-bold uppercase tracking-[.22em] text-rose">Our story</p><h2 className="serif text-4xl font-semibold md:text-5xl">A bakery built around the feeling of home.</h2><p className="mt-6 leading-8 text-ivory/65">Born from a love for Indian flavours and European baking, Crème & Crust brings together familiar tastes and modern craftsmanship. Every loaf, pastry and cake is prepared in small batches using carefully selected ingredients.</p><div className="mt-9 grid grid-cols-2 gap-5 border-t border-white/15 pt-7 sm:grid-cols-4">{[['15+','Signature Bakes'],['100%','Fresh Daily'],['4.9/5','Customer Rating'],['1000+','Happy Customers']].map(([n,l])=><div key={l}><p className="serif text-3xl font-semibold text-rose">{n}</p><p className="mt-1 text-xs text-ivory/55">{l}</p></div>)}</div></div></div></section>}
function Bestseller({onAdd}){return <section className="px-5 py-24"><div className="mx-auto max-w-7xl overflow-hidden rounded-[34px] bg-gradient-to-br from-[#f1dfd4] to-[#fbf7f0] p-3 shadow-soft"><div className="grid items-center gap-8 overflow-hidden rounded-[27px] bg-white/30 lg:grid-cols-2"><div className="img-zoom overflow-hidden rounded-[27px]"><img src={IMG.dessert} className="h-[470px] w-full object-cover"/></div><div className="p-7 md:p-12"><span className="inline-flex items-center gap-2 rounded-full bg-rose/15 px-3 py-1.5 text-xs font-bold uppercase tracking-wider text-mocha">★ Bestseller</span><h2 className="serif mt-5 text-4xl font-semibold">Rasmalai Tres Leches</h2><p className="mt-4 max-w-lg leading-7 text-chocolate/65">Soft milk-soaked sponge, cardamom cream, saffron notes and delicate rasmalai-inspired layers. A celebration cake with an unmistakably Indian heart.</p><div className="mt-5 flex items-center gap-1 text-rose">{[1,2,3,4,5].map(i=><Star key={i} size={17} fill="currentColor"/>)} <span className="ml-2 text-sm text-chocolate/60">4.9 · 128 reviews</span></div><div className="mt-8 flex items-center gap-4"><span className="text-2xl font-bold text-mocha">₹750</span><Button onClick={()=>onAdd(products[4])}>Add to Cart <ShoppingBag size={16}/></Button></div></div></div></div></section>}
function CustomCake(){return <section className="px-5 pb-24"><div className="mx-auto grid max-w-7xl overflow-hidden rounded-[34px] bg-[#ead4c6] lg:grid-cols-[.9fr_1.1fr]"><div className="img-zoom min-h-[500px]"><img src={IMG.cake} className="h-full w-full object-cover"/></div><div className="p-7 md:p-12"><p className="text-xs font-bold uppercase tracking-[.22em] text-mocha">Celebrations, your way</p><h2 className="serif mt-2 text-4xl font-semibold">Made For Your Moments.</h2><p className="mt-4 leading-7 text-chocolate/65">Birthdays, weddings, anniversaries, baby showers or corporate celebrations — tell us what you are imagining.</p><div className="glass mt-7 rounded-[24px] p-5"><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold">Occasion<select className="mt-2 w-full rounded-xl border border-rose/20 bg-white/65 px-3 py-3 text-sm outline-none"><option>Birthday</option><option>Wedding</option><option>Anniversary</option><option>Baby Shower</option><option>Corporate</option></select></label><label className="text-xs font-semibold">Cake flavor<select className="mt-2 w-full rounded-xl border border-rose/20 bg-white/65 px-3 py-3 text-sm outline-none"><option>Rasmalai</option><option>Chocolate</option><option>Pistachio Rose</option><option>Kesar Pista</option></select></label><label className="text-xs font-semibold">Size<select className="mt-2 w-full rounded-xl border border-rose/20 bg-white/65 px-3 py-3 text-sm outline-none"><option>0.5 kg</option><option>1 kg</option><option>1.5 kg</option><option>2 kg+</option></select></label><label className="text-xs font-semibold">Preferred date<input type="date" className="mt-2 w-full rounded-xl border border-rose/20 bg-white/65 px-3 py-3 text-sm outline-none"/></label></div><Button className="mt-5 w-full">Design Your Cake <ArrowRight size={16}/></Button></div></div></div></section>}
function Testimonials(){
  const reviews=[
    ['Ananya R.','The Rasmalai Tres Leches is absolutely incredible. The perfect balance between traditional and modern.'],
    ['Meera S.','Everything tastes freshly made, and the packaging is beautiful. Their cakes have become our family celebration tradition.'],
    ['Rahul K.','The pistachio rose cake was easily the highlight of our birthday party.']
  ];
  return (
    <section className="bg-white/45 px-5 py-24">
      <div className="mx-auto max-w-7xl">
        <SectionTitle eyebrow="Kind words" title="Made to be remembered." />
        <div className="grid gap-5 md:grid-cols-3">
          {reviews.map(([name, review]) => (
            <div key={name} className="glass lift rounded-[25px] p-7">
              <div className="flex gap-1 text-rose">
                {[1,2,3,4,5].map((star) => (
                  <Star key={star} size={15} fill="currentColor" />
                ))}
              </div>
              <p className="serif mt-5 text-xl leading-8">“{review}”</p>
              <p className="mt-6 text-sm font-semibold">{name}</p>
              <p className="mt-1 text-xs text-chocolate/45">Verified customer</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
function Gallery(){const pics=[IMG.croissant,IMG.chocolate,IMG.dessert,IMG.bread,IMG.coffee,IMG.interior,IMG.baker,IMG.tart];return <section className="px-5 py-24"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between gap-5"><SectionTitle eyebrow="@cremeandcrust" title="A little sweetness on your feed."/><a href="#contact" className="mb-10 hidden items-center gap-2 text-sm font-semibold text-mocha sm:flex">Follow along <ArrowRight size={15}/></a></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{pics.map((p,i)=><div key={i} className={`img-zoom overflow-hidden rounded-2xl ${i===0||i===5?'md:row-span-2':''}`}><img src={p} className={`h-full w-full object-cover ${i===0||i===5?'min-h-[390px]':'min-h-[185px]'}`}/></div>)}</div></div></section>}
function Contact(){return <section id="contact" className="px-5 pb-24"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[30px] bg-chocolate p-7 text-ivory md:p-10"><p className="text-xs font-bold uppercase tracking-[.22em] text-rose">Come say hello</p><h2 className="serif mt-2 text-4xl font-semibold">Your neighbourhood bakery, made a little special.</h2><div className="mt-9 space-y-5 text-sm text-ivory/70"><p className="flex gap-3"><MapPin className="shrink-0 text-rose" size={20}/> MVP Colony, Visakhapatnam, Andhra Pradesh</p><p className="flex gap-3"><Clock3 className="shrink-0 text-rose" size={20}/> Monday–Sunday · 8:00 AM – 9:00 PM</p><p className="flex gap-3"><Phone className="shrink-0 text-rose" size={20}/> +91 98765 43210</p><p className="flex gap-3"><Mail className="shrink-0 text-rose" size={20}/> hello@cremeandcrust.in</p></div></div><div className="glass relative min-h-[360px] overflow-hidden rounded-[30px] p-4"><div className="absolute inset-4 rounded-[23px] bg-[#eadfd5] opacity-80"/><div className="absolute inset-0 grid place-items-center"><div className="glass rounded-2xl px-6 py-5 text-center"><MapPin className="mx-auto text-rose"/><p className="serif mt-2 text-xl font-semibold">MVP Colony</p><p className="text-xs text-chocolate/55">Visakhapatnam</p><Button secondary className="mt-4">Get Directions</Button></div></div><div className="absolute left-10 top-12 h-2 w-2 rounded-full bg-rose"/><div className="absolute right-16 bottom-20 h-3 w-3 rounded-full bg-mocha"/></div></div></section>}
function Footer(){return <footer className="bg-chocolate px-5 py-14 text-ivory"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-4"><div className="md:col-span-2"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-rose"><Croissant size={21}/></span><span className="serif text-2xl font-semibold">Crème & Crust</span></div><p className="mt-5 max-w-sm text-sm leading-6 text-ivory/55">Handcrafted with warmth, baked with tradition. Modern Indian bakes for everyday cravings and life's sweetest moments.</p><div className="mt-6 flex gap-2"><a className="grid h-10 w-10 place-items-center rounded-full border border-white/10 hover:bg-white/10"><Instagram size={17}/></a><a className="grid h-10 w-10 place-items-center rounded-full border border-white/10 hover:bg-white/10"><Facebook size={17}/></a></div></div><div><p className="font-semibold">Explore</p><div className="mt-4 space-y-3 text-sm text-ivory/55"><a className="block hover:text-ivory" href="#menu">Menu</a><a className="block hover:text-ivory" href="#story">Our Story</a><a className="block hover:text-ivory" href="#specialties">Specialties</a><a className="block hover:text-ivory" href="#contact">Contact</a></div></div><div><p className="font-semibold">Hours</p><p className="mt-4 text-sm leading-6 text-ivory/55">Monday – Sunday<br/>8:00 AM – 9:00 PM</p><p className="mt-5 text-sm text-ivory/55">MVP Colony, Vizag</p></div></div><div className="mx-auto mt-12 max-w-7xl border-t border-white/10 pt-6 text-xs text-ivory/35">© 2026 Crème & Crust. Crafted with warmth in Visakhapatnam.</div></footer>}
function Cart({items,onClose,onChange}){const total=items.reduce((s,x)=>s+x.price*x.qty,0);return <><div onClick={onClose} className="fixed inset-0 z-[60] bg-chocolate/25 backdrop-blur-sm"/><aside className="fixed right-0 top-0 z-[70] flex h-full w-full max-w-md flex-col bg-ivory p-5 shadow-2xl"><div className="flex items-center justify-between border-b border-rose/15 pb-5"><div><p className="text-xs font-bold uppercase tracking-widest text-rose">Your basket</p><h2 className="serif text-2xl font-semibold">Freshly packed for you</h2></div><button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-full hover:bg-white"><X/></button></div><div className="hide-scroll flex-1 space-y-4 overflow-y-auto py-5">{!items.length?<div className="grid h-full place-items-center text-center"><ShoppingBag className="mx-auto text-rose" size={40}/><p className="serif mt-4 text-2xl font-semibold">Your basket is empty</p><p className="mt-2 text-sm text-chocolate/50">Add a little sweetness to get started.</p></div>:items.map(x=><div key={x.id} className="glass flex gap-3 rounded-2xl p-3"><img src={x.img} className="h-20 w-20 rounded-xl object-cover"/><div className="min-w-0 flex-1"><p className="font-semibold">{x.name}</p><p className="mt-1 text-sm text-mocha">₹{x.price}</p><div className="mt-2 flex items-center gap-2"><button onClick={()=>onChange(x.id,-1)} className="grid h-7 w-7 place-items-center rounded-full bg-white"><Minus size={13}/></button><span className="text-sm font-semibold">{x.qty}</span><button onClick={()=>onChange(x.id,1)} className="grid h-7 w-7 place-items-center rounded-full bg-white"><Plus size={13}/></button></div></div><button onClick={()=>onChange(x.id,-x.qty)} className="self-start text-chocolate/40 hover:text-rose"><Trash2 size={16}/></button></div>)}</div>{items.length>0&&<div className="border-t border-rose/15 pt-5"><div className="flex justify-between"><span className="text-sm text-chocolate/60">Subtotal</span><span className="font-bold">₹{total}</span></div><Button className="mt-4 w-full">Proceed to Order <ArrowRight size={16}/></Button></div>}</aside></>}
function Toast({message}){if(!message)return null;return <div className="fixed bottom-5 left-1/2 z-[90] flex -translate-x-1/2 items-center gap-2 rounded-full bg-chocolate px-5 py-3 text-sm font-semibold text-ivory shadow-xl"><span className="grid h-5 w-5 place-items-center rounded-full bg-rose"><Check size={13}/></span>{message}</div>}
function App(){const[cart,setCart]=useState([]);const[favs,setFavs]=useState([]);const[cartOpen,setCartOpen]=useState(false);const[toast,setToast]=useState('');const add=p=>{setCart(c=>{const hit=c.find(x=>x.id===p.id);return hit?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]});setToast(`${p.name} added to basket`);setCartOpen(false);};const change=(id,d)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:x.qty+d}:x).filter(x=>x.qty>0));useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2200);return()=>clearTimeout(t)},[toast]);return <div className="min-h-screen overflow-x-hidden bg-ivory text-chocolate"><Navbar cartCount={cart.reduce((s,x)=>s+x.qty,0)} onCart={()=>setCartOpen(true)}/><Hero/><MenuSection onAdd={add} favs={favs} onFav={id=>setFavs(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id])}/><Specialties/><Story/><Bestseller onAdd={add}/><CustomCake/><Testimonials/><Gallery/><Contact/><section className="px-5 pb-20"><div className="mx-auto max-w-7xl overflow-hidden rounded-[32px] bg-gradient-to-br from-mocha to-chocolate p-8 text-center text-ivory md:p-14"><p className="text-xs font-bold uppercase tracking-[.22em] text-rose">Freshly baked, always</p><h2 className="serif mt-3 text-4xl font-semibold md:text-5xl">Your next favourite bake is waiting.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-ivory/65">Fresh pastries, celebration cakes and little moments of sweetness — made fresh every day.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Button>Order Now</Button><Button secondary className="border-white/20 bg-white/10 text-ivory hover:bg-white/20">View Menu</Button></div></div></section><Footer/>{cartOpen&&<Cart items={cart} onClose={()=>setCartOpen(false)} onChange={change}/>}<Toast message={toast}/></div>}

createRoot(document.getElementById('root')).render(<App/>);
